theme: minima
markdown: kramdown

title: Learning Purely Tactile In-Hand Manipulation
author: "{leon.sievers,johannes.pitz,lennart.roestel,dominik.winkelbauer,berthold.baeuml}@tum.de"

include:
    - _pages
    
plugins:
  - jekyll-redirect-from

exclude:
    - .gitignore
    - Gemfile
    - README.md
